# Generated by Django 5.2.3 on 2025-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_irid_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book'), ('chapter', 'Book Chapter'), ('report', 'Technical Report'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('paper', 'Paper'), ('book', 'Book'), ('presentation', 'Presentation'), ('video', 'Video'), ('dataset', 'Dataset'), ('code', 'Code'), ('other', 'Other')], max_length=20),
        ),
    ]
